name: ingenico_sdk
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ingenico_platform_interface:
    git:
      url: git://github.com/bamlab/ingenico-flutter-sdk.git
      path: packages/ingenico_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^1.0.6

flutter:
  plugin:
    platforms:
      android:
        package: com.ingenico.flutter_sdk
        pluginClass: IngenicoSdkPlugin
      ios:
        pluginClass: IngenicoSdk
